// definition parser
// var words = [];
// for(let prop in data.advanced_vi){
// 	words.push(data.advanced_vi[prop].meaning_1)
// }
// console.log(words);


let definitionList = [ 'verb: change or alter in form, appearance, or nature',
  'adjective: highly or widely praised or boasted about',
  'adjective: brave; bold; courageous',
  'noun: injustice by virtue of not conforming with rules or standards',
  'adjective: transparently clear; easily understandable',
  'adjective: immune to attack; without flaws',
  'adjective: expressing sorrow',
  'verb: cause one, through routine, to lose energy and enthusiasm',
  'adjective: never to be broken, infringed, or dishonored',
  'verb: to give or take something by force',
  'adjective: intellectually productive',
  'noun: something desired as a necessity',
  'adjective: characterized by lightness and insubstantiality',
  'adjective: slow to learn or understand; lacking intellectual acuity; lacking in insight or discernment',
  'noun: an act of extreme wickedness',
  'noun: resourcefulness and determination',
  'adjective: showing sorrow',
  'adjective: free of guilt; not subject to blame; beyond doubt or reproach',
  'adjective: reluctant to draw attention to yourself',
  'verb: formally reject or give up (as a belief)',
  'adjective: showing a cheerful willingness to do favors for others',
  'noun: a trite or obvious remark',
  'adjective: Associated with or participating in an activity, especially one of a questionable nature.',
  'noun: a pauper who lives by begging',
  'adjective: having an extremely bad smell',
  'adjective: characteristic of an absolute ruler or absolute rule; having absolute sovereignty',
  'noun: someone new to a field or activity',
  'noun: overbearing pride evidenced by a superior manner toward inferiors',
  'adjective: acceptable to the taste or mind',
  'verb: attack as false or wrong',
  'adjective: not admitting of passage or capable of being affected',
  'verb: mix together different elements or concepts',
  'verb: provide with an opportunity',
  'verb: command against',
  'adjective: young and inexperienced',
  'adjective: being of equal extent or scope or duration',
  'verb: the act of restraining power or action or limiting excess',
  'noun: a very intense and uncontrolled fire',
  'verb: convert (someone) to another religion, philosophy, or perspective',
  'adjective: uninteresting, lacking vitality',
  'adverb: with care and persistence',
  'noun: great coolness and composure under strain',
  'noun: someone shirking their duty by pretending to be sick or incapacitated',
  'adjective: arrived at without due care or effort; lacking depth',
  'noun: a formal expression of praise',
  'adjective: (of e.g. speech and writing) tending to depart from the main point',
  'adjective: (of language) pompous and tedious',
  'verb: talk in a dogmatic and pompous manner',
  'adjective: (of conflict) within a group or organization',
  'adjective: showing hovering attentiveness' ]

let wordList = [ 'transmute',
  'vaunted',
  'doughty',
  'inequity',
  'pellucid',
  'unassailable',
  'elegiac',
  'stultify',
  'inviolable',
  'appropriate',
  'fecund',
  'desideratum',
  'ethereal',
  'obtuse',
  'enormity',
  'gumption',
  'dolorous',
  'unimpeachable',
  'self-effacing',
  'abjure',
  'complaisant',
  'bromide',
  'complicit',
  'mendicant',
  'noisome',
  'autocratic',
  'tyro',
  'hauteur',
  'palatable',
  'impugn',
  'impervious',
  'conflate',
  'afford',
  'proscribe',
  'callow',
  'coterminous',
  'bridle',
  'conflagration',
  'proselytize',
  'desiccated',
  'assiduously',
  'aplomb',
  'malingerer',
  'facile',
  'panegyric',
  'discursive',
  'turgid',
  'pontificate',
  'internecine',
  'solicitous',
  'fawn',
  'profusion',
  'buttress',
  'conundrum',
  'humdrum',
  'begrudge',
  'precarious',
  'rile',
  'redress',
  'deride',
  'antedate',
  'prevail',
  'industrious',
  'wanton',
  'evenhanded',
  'rakish',
  'behoove',
  'cerebral',
  'glean',
  'cohesive',
  'coalesce',
  'tribulation',
  'incumbent',
  'analogous',
  'finagle',
  'lethargic',
  'delegate',
  'melancholy',
  'avert',
  'emulate',
  'eccentric',
  'ascribe',
  'clemency',
  'belittle',
  'docile',
  'implicate',
  'besmirch',
  'foolhardy',
  'intermittent',
  'piquant',
  'insipid',
  'preempt',
  'incense',
  'irascible',
  'presumptuous',
  'consecrate',
  'uncanny',
  'cavalier',
  'veneer',
  'forthright',
  ]